const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'@playwright/test');
const root=path.resolve(__dirname,'..'),out=path.join(root,'docs/evidence/art-direction'),shots=path.join(root,'docs/screenshots/art-direction');
(async()=>{const browser=await chromium.launch({channel:process.env.PLAYWRIGHT_CHANNEL||'msedge',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});const ids=['overview','result','tls','recovery','operations','rollback','artifacts','evidence'];const review={checkedAt:new Date().toISOString(),scope:'Static report, identical historical records and generation clock; no operation executed',views:[],fonts:[],network:[],comparisons:[]};
page.on('request',r=>{if(!['file:','data:'].some(p=>r.url().startsWith(p)))review.network.push(r.url());});
const urls={baseline:'file:///'+path.join(root,'.runtime/art-direction/baseline.html').replaceAll('\\','/'),candidate:'file:///'+path.join(root,'docs/report.html').replaceAll('\\','/')};
for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:1000});for(const id of ids){for(const mode of ['baseline','candidate']){await page.goto(urls[mode]+'#'+id);await page.locator('#'+id+':visible').waitFor();await page.evaluate(()=>document.fonts.ready);const fields=await page.locator('#'+id).evaluate(el=>({times:[...el.querySelectorAll('time')].map(e=>e.getAttribute('datetime')),proofs:[...el.querySelectorAll('a[href]')].map(e=>e.getAttribute('href')),values:[...el.querySelectorAll('code')].map(e=>e.textContent)}));review.comparisons.push({mode,width,id,fields});await page.mouse.move(0,0);await page.evaluate(()=>{document.activeElement?.blur();scrollTo(0,0)});if(width===1440||width===390)await page.screenshot({path:path.join(shots,`${mode}-${id}-${width}.png`),fullPage:true});if(mode==='baseline')continue;
const metrics=await page.locator('#'+id).evaluate(el=>{const rgb=v=>v.match(/[\d.]+/g).map(Number);const lum=c=>c.slice(0,3).map(n=>{n/=255;return n<=.04045?n/12.92:((n+.055)/1.055)**2.4}).reduce((s,n,i)=>s+n*[.2126,.7152,.0722][i],0);const bg=e=>{while(e){let c=rgb(getComputedStyle(e).backgroundColor);if(c.length<4||c[3]===1)return c;e=e.parentElement}return[255,255,255]};const failures=[];let checked=0,min=99;for(const e of document.querySelectorAll('body *')){if(!e.checkVisibility({checkVisibilityCSS:true})||![...e.childNodes].some(n=>n.nodeType===3&&n.textContent.trim()))continue;const s=getComputedStyle(e),l1=lum(rgb(s.color)),l2=lum(bg(e)),ratio=(Math.max(l1,l2)+.05)/(Math.min(l1,l2)+.05),large=parseFloat(s.fontSize)>=24||(parseFloat(s.fontSize)>=18.66&&parseInt(s.fontWeight)>=700);checked++;min=Math.min(min,ratio);if(ratio<(large?3:4.5))failures.push({text:e.textContent.slice(0,70),ratio});}return{overflow:document.documentElement.scrollWidth>innerWidth,contrast:{checked,min,failures},visibleApprovalsInNav:[...document.querySelectorAll('.operation-meta')].filter(e=>e.checkVisibility()).map(e=>e.textContent)}});assert.equal(metrics.overflow,false);assert.deepEqual(metrics.contrast.failures,[]);assert.ok(!metrics.visibleApprovalsInNav.includes('Aprovado'));review.views.push({width,id,...metrics});}
const pair=review.comparisons.slice(-2);assert.deepEqual(pair[0].fields.times,pair[1].fields.times);assert.deepEqual(pair[0].fields.proofs.sort(),pair[1].fields.proofs.sort());assert.deepEqual(pair[0].fields.values.sort(),pair[1].fields.values.sort());}}
await page.goto(urls.candidate+'#result');await page.evaluate(()=>document.fonts.ready);const cdp=await page.context().newCDPSession(page);await cdp.send('DOM.enable');await cdp.send('CSS.enable');const {root:dom}=await cdp.send('DOM.getDocument');for(const selector of ['#result-title','.job h3','.job-values dd']){const{nodeId}=await cdp.send('DOM.querySelector',{nodeId:dom.nodeId,selector});const{fonts}=await cdp.send('CSS.getPlatformFontsForNode',{nodeId});assert.ok(fonts.every(f=>f.isCustomFont));review.fonts.push({selector,fonts});}
await page.context().setOffline(true);await page.reload();await page.locator('#result:visible').waitFor();assert.ok(await page.locator('#result .job-values').isVisible());await page.locator('.operation-picker summary').click();await page.getByRole('link',{name:'Backup e restauração',exact:true}).click();await page.locator('#recovery:visible').waitFor();review.offline={reload:true,navigation:true,scope:'file report with embedded font, brand, CSS and JavaScript'};assert.deepEqual(review.network,[]);
review.sizes={baselineBytes:fs.statSync(path.join(root,'.runtime/art-direction/baseline.html')).size,candidateBytes:fs.statSync(path.join(root,'docs/report.html')).size};
fs.writeFileSync(path.join(out,'audit.json'),JSON.stringify(review,null,2)+'\n');await browser.close();console.log(JSON.stringify({views:review.views.length,dataPairs:review.comparisons.length/2,fonts:review.fonts,offline:review.offline,sizes:review.sizes}));})();
